In [2]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [3]:
i = 1
while i <= 10:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


In [4]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [9]:
def rss(x,y):
    out = (x**2 + y**2) ** (0.5)
    return out

In [12]:
# python package is a collection of python modules

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
#help(np.vstack)

A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

B = np.array([[2,4,6],
              [8,10,12],
              [14,16,18]])

B = np.hstack(A, B)
print(A)
print(B)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [37]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [32]:
np.shape(A)

(3, 3)

In [33]:
print(A)
print(np.transpose(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [36]:
print(np.hstack(A,B))

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [54]:
def mult_x(a,b,mult=2,validation=0):
    c = mult * a * b
    if validation == 1:
        print('Youre doing great!')
    if validation == -1:
        print('Get good pls')
    return c

In [55]:
mult_x(2,3)

12

In [56]:
mult_x(2,3,mult=4)

24

In [57]:
mult_x(2,3,mult=4,validation=1)

Youre doing great!


24

In [59]:
mult_x(2,3,mult=5,validation=-1)

Get good pls


30

In [78]:
import random as rd
#help(rd.random)

a = rd.random()
if a < .33333:
    b=-1
elif a > .66666:
    b=1
else:
    b=0
    
mult_x(2,3,mult=5,validation=b)

Get good pls


30